/*
 * cdda.c — CDDA virtual file backend
 *
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Presents audio CD tracks as virtual WAV or AIFF files. The file
 * header is synthesized on-the-fly; audio data is read via the media
 * layer (SCSI Read CD on Amiga hardware).
 *
 * On mixed-mode discs (data + audio), tracks appear in a virtual
 * CDDA/ subdirectory so they don't mix with data files. On pure
 * audio CDs, tracks appear at the root.
 *
 * Track detection requires a TOC from the media layer. On host
 * images without TOC support, the backend will not activate.
 */

#include "cdda.h"
#include "odfs/alloc.h"
#include "odfs/cache.h"
#include "odfs/log.h"
#include "odfs/error.h"
#include "odfs/printf.h"
#include "odfs/string.h"

#include <string.h>
#include <inttypes.h>
#include <stdarg.h>

#define CDDA_CDDB_NAME "CDDB.txt"
#define CDDA_CDDB_NODE_ID 0x43444442u
#define CDDA_CDDB_LBA 1u

/* ------------------------------------------------------------------ */
/* Header generation                                                   */
/* ------------------------------------------------------------------ */

static void cdda_write_le16(uint8_t *p, uint16_t v)
{
    p[0] = (uint8_t)(v);
    p[1] = (uint8_t)(v >> 8);
}

static void cdda_write_le32(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)(v);
    p[1] = (uint8_t)(v >> 8);
    p[2] = (uint8_t)(v >> 16);
    p[3] = (uint8_t)(v >> 24);
}

static void cdda_write_be16(uint8_t *p, uint16_t v)
{
    p[0] = (uint8_t)(v >> 8);
    p[1] = (uint8_t)(v);
}

static void cdda_write_be32(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)(v >> 24);
    p[1] = (uint8_t)(v >> 16);
    p[2] = (uint8_t)(v >> 8);
    p[3] = (uint8_t)(v);
}

static uint32_t cdda_header_size(cdda_file_format_t format)
{
    return (format == CDDA_FILE_FORMAT_AIFF)
        ? CDDA_AIFF_HEADER_SIZE
        : CDDA_WAV_HEADER_SIZE;
}

static uint32_t cdda_sum_digits(uint32_t value)
{
    uint32_t sum = 0;

    do {
        sum += value % 10u;
        value /= 10u;
    } while (value != 0);

    return sum;
}

static uint32_t cdda_track_offset_frames(const cdda_track_t *track)
{
    return track->start_lba + 150u;
}

static uint32_t cdda_total_seconds(const cdda_context_t *ctx)
{
    uint32_t first_frames;
    uint32_t leadout_frames;
    const cdda_track_t *last;

    if (ctx->track_count == 0)
        return 0;

    first_frames = cdda_track_offset_frames(&ctx->tracks[0]);
    last = &ctx->tracks[ctx->track_count - 1];
    leadout_frames = cdda_track_offset_frames(last) + last->length_frames;
    return (leadout_frames / CDDA_FRAMES_PER_SEC) -
           (first_frames / CDDA_FRAMES_PER_SEC);
}

static uint32_t cdda_disc_id(const cdda_context_t *ctx)
{
    uint32_t sum = 0;

    for (int i = 0; i < ctx->track_count; i++)
        sum += cdda_sum_digits(cdda_track_offset_frames(&ctx->tracks[i]) /
                               CDDA_FRAMES_PER_SEC);

    return ((sum % 255u) << 24) |
           (cdda_total_seconds(ctx) << 8) |
           (uint32_t)ctx->track_count;
}

static int cdda_appendf(char *buf, size_t buf_size, size_t *used,
                        const char *fmt, ...)
{
    va_list ap;
    int wrote;

    if (*used >= buf_size)
        return 0;

    va_start(ap, fmt);
    wrote = odfs_vsnprintf(buf + *used, buf_size - *used, fmt, ap);
    va_end(ap);

    if (wrote < 0 || (size_t)wrote >= buf_size - *used)
        return 0;

    *used += (size_t)wrote;
    return 1;
}

static void cdda_generate_cddb(cdda_context_t *ctx)
{
    char *text;
    size_t text_size;
    size_t used = 0;
    uint32_t disc_id;
    uint32_t total_seconds;

    if (ctx->track_count == 0)
        return;

    text_size = 256u + (size_t)ctx->track_count * 48u;
    text = odfs_malloc(text_size);
    if (!text)
        return;

    disc_id = cdda_disc_id(ctx);
    total_seconds = cdda_total_seconds(ctx);

    if (!cdda_appendf(text, text_size, &used,
                      "# Generated by ODFileSystem from disc TOC\n"
                      "DISCID=%08" PRIx32 "\n"
                      "TRACKS=%d\n"
                      "TOTAL_SECONDS=%" PRIu32 "\n"
                      "TOTAL_FRAMES=%" PRIu32 "\n",
                      disc_id, ctx->track_count,
                      total_seconds,
                      total_seconds * CDDA_FRAMES_PER_SEC)) {
        odfs_free(text);
        return;
    }

    for (int i = 0; i < ctx->track_count; i++) {
        if (!cdda_appendf(text, text_size, &used,
                          "OFFSET%02d=%" PRIu32 "\n",
                          i + 1,
                          cdda_track_offset_frames(&ctx->tracks[i]))) {
            odfs_free(text);
            return;
        }
    }

    if (!cdda_appendf(text, text_size, &used,
                      "QUERY=cddb query %08" PRIx32 " %d",
                      disc_id, ctx->track_count)) {
        odfs_free(text);
        return;
    }

    for (int i = 0; i < ctx->track_count; i++) {
        if (!cdda_appendf(text, text_size, &used,
                          " %" PRIu32,
                          cdda_track_offset_frames(&ctx->tracks[i]))) {
            odfs_free(text);
            return;
        }
    }

    if (!cdda_appendf(text, text_size, &used, " %" PRIu32 "\n",
                      total_seconds)) {
        odfs_free(text);
        return;
    }

    ctx->cddb_text = text;
    ctx->cddb_size = used;
}

static int cdda_fill_cddb_node(const cdda_context_t *ctx, odfs_node_t *node)
{
    if (!ctx->cddb_text || ctx->cddb_size == 0)
        return 0;

    memset(node, 0, sizeof(*node));
    node->id = CDDA_CDDB_NODE_ID;
    node->parent_id = 0;
    node->backend = ODFS_BACKEND_CDDA;
    node->kind = ODFS_NODE_VIRTUAL;
    node->size = ctx->cddb_size;
    node->extent.lba = CDDA_CDDB_LBA;
    node->extent.length = (uint32_t)ctx->cddb_size;
    memcpy(node->name, CDDA_CDDB_NAME, sizeof(CDDA_CDDB_NAME));
    return 1;
}

static void cdda_byteswap_samples(uint8_t *buf, size_t len)
{
    size_t i;

    for (i = 0; i + 1 < len; i += 2) {
        uint8_t tmp = buf[i];
        buf[i] = buf[i + 1];
        buf[i + 1] = tmp;
    }
}

/*
 * Build a 44-byte PCM WAV header for the given data size.
 */
static void cdda_build_wav_header(uint8_t *hdr, uint32_t data_size)
{
    uint32_t byte_rate = CDDA_SAMPLE_RATE * CDDA_CHANNELS * (CDDA_BITS_PER_SAMPLE / 8);
    uint16_t block_align = CDDA_CHANNELS * (CDDA_BITS_PER_SAMPLE / 8);

    memcpy(&hdr[0], "RIFF", 4);
    cdda_write_le32(&hdr[4], 36 + data_size);  /* file size - 8 */
    memcpy(&hdr[8], "WAVE", 4);
    memcpy(&hdr[12], "fmt ", 4);
    cdda_write_le32(&hdr[16], 16);              /* fmt chunk size */
    cdda_write_le16(&hdr[20], 1);               /* PCM format */
    cdda_write_le16(&hdr[22], CDDA_CHANNELS);
    cdda_write_le32(&hdr[24], CDDA_SAMPLE_RATE);
    cdda_write_le32(&hdr[28], byte_rate);
    cdda_write_le16(&hdr[32], block_align);
    cdda_write_le16(&hdr[34], CDDA_BITS_PER_SAMPLE);
    memcpy(&hdr[36], "data", 4);
    cdda_write_le32(&hdr[40], data_size);
}

static void cdda_build_aiff_header(uint8_t *hdr, uint32_t data_size)
{
    static const uint8_t rate_44100[10] = {
        0x40, 0x0e, 0xac, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    };
    uint32_t sample_frames = data_size /
                             (CDDA_CHANNELS * (CDDA_BITS_PER_SAMPLE / 8));

    memcpy(&hdr[0], "FORM", 4);
    cdda_write_be32(&hdr[4], 46 + data_size);
    memcpy(&hdr[8], "AIFF", 4);
    memcpy(&hdr[12], "COMM", 4);
    cdda_write_be32(&hdr[16], 18);
    cdda_write_be16(&hdr[20], CDDA_CHANNELS);
    cdda_write_be32(&hdr[22], sample_frames);
    cdda_write_be16(&hdr[26], CDDA_BITS_PER_SAMPLE);
    memcpy(&hdr[28], rate_44100, sizeof(rate_44100));
    memcpy(&hdr[38], "SSND", 4);
    cdda_write_be32(&hdr[42], 8 + data_size);
    cdda_write_be32(&hdr[46], 0);
    cdda_write_be32(&hdr[50], 0);
}

static void cdda_build_header(cdda_file_format_t format,
                              uint8_t *hdr,
                              uint32_t data_size)
{
    if (format == CDDA_FILE_FORMAT_AIFF)
        cdda_build_aiff_header(hdr, data_size);
    else
        cdda_build_wav_header(hdr, data_size);
}

/* ------------------------------------------------------------------ */
/* node IDs and encoding                                               */
/* ------------------------------------------------------------------ */

/*
 * Node ID encoding for CDDA:
 *   0          = root (or CDDA/ virtual dir on mixed-mode)
 *   1..99      = track number
 *   extent.lba = track index + 2 into tracks[] array (for quick lookup)
 */

static void cdda_track_name(int track_num,
                            cdda_file_format_t format,
                            char *buf,
                            size_t buf_size)
{
    const char *ext = (format == CDDA_FILE_FORMAT_AIFF) ? "aiff" : "wav";
    int len = 0;

    (void)buf_size;

    buf[len++] = 'T';
    buf[len++] = 'r';
    buf[len++] = 'a';
    buf[len++] = 'c';
    buf[len++] = 'k';
    buf[len++] = '0' + (track_num / 10);
    buf[len++] = '0' + (track_num % 10);
    buf[len++] = '.';
    while (*ext)
        buf[len++] = *ext++;
    buf[len] = '\0';
}

/* ------------------------------------------------------------------ */
/* probe                                                               */
/* ------------------------------------------------------------------ */

static odfs_err_t cdda_probe(odfs_cache_t *cache,
                               odfs_log_state_t *log,
                               uint32_t session_start)
{
    (void)cache;
    (void)session_start;

    /*
     * CDDA detection requires a TOC from the device. We can't probe
     * from the cache alone — the media layer's read_toc must work.
     * Since probe() doesn't have access to the media handle, we
     * always return BAD_FORMAT here. CDDA activation is handled
     * specially in mount.c after all other backends have been tried.
     *
     * TODO: add a cdda_probe_media() that takes odfs_media_t*
     * and is called from mount.c directly.
     */
    ODFS_DEBUG(log, ODFS_SUB_CDDA,
                "CDDA probe: requires TOC (not available from cache)");
    return ODFS_ERR_BAD_FORMAT;
}

/* ------------------------------------------------------------------ */
/* mount                                                               */
/* ------------------------------------------------------------------ */

/*
 * Mount a CDDA "filesystem" from a TOC. This is called directly
 * from mount.c, not through the standard probe→mount path, because
 * CDDA needs the media handle for TOC reading.
 *
 * Returns ODFS_OK if audio tracks were found.
 */
odfs_err_t cdda_mount_from_toc(const odfs_toc_t *toc,
                               int has_data_session,
                               const odfs_mount_opts_t *opts,
                               odfs_media_t *media,
                               odfs_node_t *root_out,
                               void **backend_ctx)
{
    cdda_context_t *ctx;
    int audio_count = 0;
    uint32_t header_size;

    ctx = odfs_calloc(1, sizeof(*ctx));
    if (!ctx)
        return ODFS_ERR_NOMEM;

    ctx->is_mixed_mode = has_data_session;
    ctx->file_format = (opts && opts->prefer_aiff)
        ? CDDA_FILE_FORMAT_AIFF
        : CDDA_FILE_FORMAT_WAV;
    ctx->media = media;
    header_size = cdda_header_size(ctx->file_format);

    for (int i = 0; i < toc->session_count && audio_count < CDDA_MAX_TRACKS; i++) {
        uint32_t start = toc->sessions[i].start_lba;
        uint32_t length = toc->sessions[i].length;

        if ((toc->sessions[i].control & 0x04) != 0)
            continue;

        if (length == 0 && i + 1 < toc->session_count)
            length = toc->sessions[i + 1].start_lba - start;
        if (length == 0 && toc->leadout_lba > start)
            length = toc->leadout_lba - start;

        if (length == 0)
            continue;

        ctx->tracks[audio_count].number = toc->sessions[i].number;
        ctx->tracks[audio_count].start_lba = start;
        ctx->tracks[audio_count].length_frames = length;
        ctx->tracks[audio_count].data_size = (uint64_t)length * CDDA_FRAME_SIZE;
        ctx->tracks[audio_count].file_size = ctx->tracks[audio_count].data_size
                                             + header_size;
        audio_count++;
    }

    ctx->track_count = audio_count;

    if (audio_count == 0) {
        odfs_free(ctx);
        return ODFS_ERR_BAD_FORMAT;
    }

    cdda_generate_cddb(ctx);

    /* build root node */
    memset(root_out, 0, sizeof(*root_out));
    root_out->id = 0;
    root_out->parent_id = 0;
    root_out->backend = ODFS_BACKEND_CDDA;
    root_out->kind = ODFS_NODE_DIR;
    if (ctx->is_mixed_mode) {
        memcpy(root_out->name, "CDDA", 5);
    } else {
        root_out->name[0] = '/';
        root_out->name[1] = '\0';
    }
    root_out->extent.lba = 0;
    root_out->extent.length = 0;

    *backend_ctx = ctx;
    return ODFS_OK;
}

static odfs_err_t cdda_mount(odfs_cache_t *cache,
                               odfs_log_state_t *log,
                               uint32_t session_start,
                               odfs_node_t *root_out,
                               void **backend_ctx)
{
    (void)cache;
    (void)log;
    (void)session_start;
    (void)root_out;
    (void)backend_ctx;
    /* standard mount path not used — see cdda_mount_from_toc() */
    return ODFS_ERR_UNSUPPORTED;
}

static void cdda_unmount(void *backend_ctx)
{
    cdda_context_t *ctx = backend_ctx;

    if (ctx) {
        odfs_free(ctx->cddb_text);
        odfs_free(ctx);
    }
}

/* ------------------------------------------------------------------ */
/* readdir                                                             */
/* ------------------------------------------------------------------ */

static odfs_err_t cdda_readdir(void *backend_ctx,
                                 odfs_cache_t *cache,
                                 odfs_log_state_t *log,
                                 const odfs_node_t *dir,
                                 odfs_dir_iter_fn callback,
                                 void *cb_ctx,
                                 uint32_t *resume_offset)
{
    cdda_context_t *ctx = backend_ctx;
    (void)cache;
    (void)log;
    (void)dir;

    int start = (resume_offset && *resume_offset) ? (int)*resume_offset : 0;

    if (start == 0) {
        odfs_node_t node;

        if (cdda_fill_cddb_node(ctx, &node)) {
            odfs_err_t err = callback(&node, cb_ctx);
            if (err != ODFS_OK) {
                if (resume_offset)
                    *resume_offset = 1;
                return err;
            }
        }
        start = 1;
    }

    for (int i = start - 1; i < ctx->track_count; i++) {
        odfs_node_t node;
        memset(&node, 0, sizeof(node));

        node.id = ctx->tracks[i].number;
        node.parent_id = 0;
        node.backend = ODFS_BACKEND_CDDA;
        node.kind = ODFS_NODE_VIRTUAL;
        node.size = ctx->tracks[i].file_size;
        node.extent.lba = (uint32_t)(i + 2);
        node.extent.length = (uint32_t)ctx->tracks[i].file_size;

        cdda_track_name(ctx->tracks[i].number, ctx->file_format,
                        node.name, sizeof(node.name));

        odfs_err_t err = callback(&node, cb_ctx);
        if (err != ODFS_OK) {
            if (resume_offset)
                *resume_offset = (uint32_t)(i + 2);
            return err;
        }
    }

    if (resume_offset)
        *resume_offset = (uint32_t)(ctx->track_count + 1);
    return ODFS_OK;
}

/* ------------------------------------------------------------------ */
/* read — synthesize header + read audio frames                        */
/* ------------------------------------------------------------------ */

static odfs_err_t cdda_read(void *backend_ctx,
                              odfs_cache_t *cache,
                              odfs_log_state_t *log,
                              const odfs_node_t *file,
                              uint64_t offset,
                              void *buf,
                              size_t *len)
{
    cdda_context_t *ctx = backend_ctx;
    (void)cache;
    (void)log;

    if (file->extent.lba == CDDA_CDDB_LBA) {
        size_t want = *len;

        if (!ctx->cddb_text || offset >= ctx->cddb_size) {
            *len = 0;
            return ODFS_OK;
        }
        if (offset + want > ctx->cddb_size)
            want = ctx->cddb_size - (size_t)offset;

        memcpy(buf, ctx->cddb_text + (size_t)offset, want);
        *len = want;
        return ODFS_OK;
    }

    int track_idx = (int)file->extent.lba - 2;
    if (track_idx < 0 || track_idx >= ctx->track_count) {
        *len = 0;
        return ODFS_ERR_NOT_FOUND;
    }

    cdda_track_t *trk = &ctx->tracks[track_idx];
    uint32_t header_size = cdda_header_size(ctx->file_format);
    size_t want = *len;
    size_t done = 0;
    uint8_t *out = buf;

    if (offset >= trk->file_size) {
        *len = 0;
        return ODFS_OK;
    }
    if (offset + want > trk->file_size)
        want = (size_t)(trk->file_size - offset);

    /* serve synthesized header bytes if offset is within the header */
    if (offset < header_size) {
        uint8_t hdr[CDDA_AIFF_HEADER_SIZE];
        cdda_build_header(ctx->file_format, hdr, (uint32_t)trk->data_size);

        size_t hdr_avail = header_size - (size_t)offset;
        size_t chunk = (hdr_avail < want) ? hdr_avail : want;
        memcpy(out, hdr + offset, chunk);
        done += chunk;
    }

    /*
     * Audio data: read via SCSI Read CD (0xBE). Any failure is returned
     * to the caller; do not mask it by synthesizing silence.
     */
    while (done < want) {
        uint64_t audio_pos = (offset + done) - header_size;
        uint32_t frame_num = (uint32_t)(audio_pos / CDDA_FRAME_SIZE);
        uint32_t frame_off = (uint32_t)(audio_pos % CDDA_FRAME_SIZE);
        uint32_t start_frame = trk->start_lba + frame_num;

        if (ctx->media && ctx->media->ops->read_audio) {
            /* read one frame at a time for simplicity */
            uint8_t frame_buf[CDDA_FRAME_SIZE];
            odfs_err_t err = odfs_media_read_audio(ctx->media,
                                                      start_frame, 1,
                                                      frame_buf);
            if (err != ODFS_OK) {
                ODFS_ERROR(log, ODFS_SUB_CDDA,
                           "audio read failed track=%d lba=%" PRIu32
                           " err=%s",
                           trk->number, start_frame, odfs_err_str(err));
                *len = 0;
                return err;
            }

            if (ctx->file_format == CDDA_FILE_FORMAT_AIFF)
                cdda_byteswap_samples(frame_buf, sizeof(frame_buf));

            size_t avail = CDDA_FRAME_SIZE - frame_off;
            size_t chunk = (avail < want - done) ? avail : want - done;
            memcpy(out + done, frame_buf + frame_off, chunk);
            done += chunk;
        } else {
            ODFS_ERROR(log, ODFS_SUB_CDDA,
                       "audio read unavailable track=%d lba=%" PRIu32,
                       trk->number, start_frame);
            *len = 0;
            return ODFS_ERR_UNSUPPORTED;
        }
    }

    *len = done;
    return ODFS_OK;
}

/* ------------------------------------------------------------------ */
/* lookup                                                              */
/* ------------------------------------------------------------------ */

static odfs_err_t cdda_lookup(void *backend_ctx,
                                odfs_cache_t *cache,
                                odfs_log_state_t *log,
                                const odfs_node_t *dir,
                                const char *name,
                                odfs_node_t *out)
{
    cdda_context_t *ctx = backend_ctx;
    (void)cache;
    (void)log;
    (void)dir;

    if (odfs_strcasecmp(name, CDDA_CDDB_NAME) == 0) {
        if (cdda_fill_cddb_node(ctx, out))
            return ODFS_OK;
        return ODFS_ERR_NOT_FOUND;
    }

    for (int i = 0; i < ctx->track_count; i++) {
        char tname[32];
        cdda_track_name(ctx->tracks[i].number, ctx->file_format,
                        tname, sizeof(tname));
        if (odfs_strcasecmp(name, tname) == 0) {
            memset(out, 0, sizeof(*out));
            out->id = ctx->tracks[i].number;
            out->parent_id = 0;
            out->backend = ODFS_BACKEND_CDDA;
            out->kind = ODFS_NODE_VIRTUAL;
            out->size = ctx->tracks[i].file_size;
            out->extent.lba = (uint32_t)(i + 2);
            out->extent.length = (uint32_t)ctx->tracks[i].file_size;
            memcpy(out->name, tname, strlen(tname) + 1);
            return ODFS_OK;
        }
    }

    return ODFS_ERR_NOT_FOUND;
}

/* ------------------------------------------------------------------ */
/* get_volume_name                                                     */
/* ------------------------------------------------------------------ */

static odfs_err_t cdda_get_volume_name(void *backend_ctx,
                                         char *buf, size_t buf_size)
{
    cdda_context_t *ctx = backend_ctx;
    const char *name = ctx->is_mixed_mode ? "CDDA" : "Audio CD";
    size_t len = strlen(name);
    if (len >= buf_size) len = buf_size - 1;
    memcpy(buf, name, len);
    buf[len] = '\0';
    return ODFS_OK;
}

/* ------------------------------------------------------------------ */
/* get_volume_size                                                     */
/* ------------------------------------------------------------------ */

static uint32_t cdda_get_volume_size(void *backend_ctx)
{
    cdda_context_t *ctx = backend_ctx;
    uint64_t bytes = 0;

    bytes += ctx->cddb_size;
    for (int i = 0; i < ctx->track_count; i++)
        bytes += ctx->tracks[i].file_size;

    uint64_t blocks = (bytes + 2047u) / 2048u;
    return blocks > UINT32_MAX ? UINT32_MAX : (uint32_t)blocks;
}

/* ------------------------------------------------------------------ */
/* backend ops table                                                   */
/* ------------------------------------------------------------------ */

const odfs_backend_ops_t cdda_backend_ops = {
    .name            = "cdda",
    .backend_type    = ODFS_BACKEND_CDDA,
    .probe           = cdda_probe,
    .mount           = cdda_mount,
    .unmount         = cdda_unmount,
    .readdir         = cdda_readdir,
    .read            = cdda_read,
    .lookup          = cdda_lookup,
    .get_volume_name = cdda_get_volume_name,
    .get_volume_size = cdda_get_volume_size,
};
